In [73]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from time import sleep
from random import randint
import math

In [74]:
population = 83.1

In [75]:
url="https://www.finanzen.net/index/dax"

In [76]:
response = requests.get(url)

In [77]:
response.status_code

200

In [78]:
in_posession={'adidas':3,'Airbus':0,'Allianz':5,'BASF':22,'Bayer':12,'Beiersdorf':3,'BMW':8,'Brenntag':2,'Commerzbank':20,'Continental':10,
 'Covestro':2,'Daimler Truck':7,'Deutsche Bank':25,'Deutsche Börse':2,'Deutsche Post':15,'Deutsche Telekom':58,'E.ON':32,'Fresenius':4,
 'Hannover Rück':0,'HeidelbergCement':2,'Henkel vz.':5,'Infineon':14,'Mercedes-Benz Group (ex Daimler)':13,'Merck':2,'MTU Aero Engines':1,
 'Münchener Rückversicherungs-Gesellschaft':2,'Porsche':0,'Porsche Automobil vz.':0,'QIAGEN':3,'Rheinmetall':0,'RWE':7,'SAP':15,
 'Sartorius vz.':1,'Siemens':10,'Siemens Energy':9,'Siemens Healthineers':14,'Symrise':0,'Volkswagen (VW) vz.':0,'Vonovia':15,'Zalando':0}

In [79]:
soup = BeautifulSoup(response.content, "html.parser")

In [80]:
#IndexShareListValues > table > tbody > tr:nth-child(1) > td:nth-child(1) > div:nth-child(1) > a
#IndexShareListValues > table > tbody > tr:nth-child(2) > td:nth-child(1) > div:nth-child(1) > a

In [81]:
soup.select("#IndexShareListValues > table > tbody> tr:nth-child(1) > td:nth-child(1) > div:nth-child(1) > a")

In [82]:
links=[]
for i in range(1,41):
    links.append(soup.select("#IndexShareListValues > table > tbody> tr:nth-child("+str(i)+") > td:nth-child(1) > div:nth-child(1) > a"))

In [83]:
links[3][0]['href']

'/aktien/basf-aktie'

In [84]:
company=[]
for i in range(40):
    company.append(links[i][0]['title'].replace(' Aktie', ''))

In [85]:
company

['adidas',
 'Airbus',
 'Allianz',
 'BASF',
 'Bayer',
 'Beiersdorf',
 'BMW',
 'Brenntag',
 'Commerzbank',
 'Continental',
 'Covestro',
 'Daimler Truck',
 'Deutsche Bank',
 'Deutsche Börse',
 'Deutsche Post',
 'Deutsche Telekom',
 'E.ON',
 'Fresenius',
 'Hannover Rück',
 'HeidelbergCement',
 'Henkel vz.',
 'Infineon',
 'Mercedes-Benz Group (ex Daimler)',
 'Merck',
 'MTU Aero Engines',
 'Münchener Rückversicherungs-Gesellschaft',
 'Porsche',
 'Porsche Automobil vz.',
 'QIAGEN',
 'Rheinmetall',
 'RWE',
 'SAP',
 'Sartorius vz.',
 'Siemens',
 'Siemens Energy',
 'Siemens Healthineers',
 'Symrise',
 'Volkswagen (VW) vz.',
 'Vonovia',
 'Zalando']

In [86]:
url2 = "https://www.finanzen.net" + links[30][0]["href"]
url2

'https://www.finanzen.net/aktien/rwe-aktie'

In [87]:
#body > main > section:nth-child(7) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)
#body > main > section:nth-child(8) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)
#body > main > section:nth-child(9) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)

In [88]:
no_shares=[]
for i in range(40):
    url2 = "https://www.finanzen.net" + links[i][0]["href"]
    response2 = requests.get(url2)
    soup = BeautifulSoup(response2.content, "html.parser")
    try:
        no_shares.append(soup.select("body > main > section:nth-child (5) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)")[0].get_text("/", strip=True))
    except:
        try:
            no_shares.append(soup.select("body > main > section:nth-child(6) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)")[0].get_text("/", strip=True))
        except:
            try:
                no_shares.append(soup.select("body > main > section:nth-child(7) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)")[0].get_text("/", strip=True))
            except:
                try:
                    no_shares.append(soup.select("body > main > section:nth-child(8) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)")[0].get_text("/", strip=True))
                except:
                    try:
                        no_shares.append(soup.select("body > main > section:nth-child(9) > div > article:nth-child(2) > div.grid.grid--gap-col-150 > div:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(2)")[0].get_text("/", strip=True))
                    except:
                        no_shares.append("0")
    wait_time = randint(1,2)
    sleep(wait_time)

In [89]:
no_shares = [s.replace('.', '') for s in no_shares]
no_shares = [s.replace(',', '.') for s in no_shares]
no_shares = ([float(x) for x in no_shares])

In [90]:
dax_df = pd.DataFrame(list(zip(company, no_shares)),
               columns =['company', 'no_shares'])

In [91]:
shares_pP=[]
for i in range(len(company)):
    shares_pP.append(math.ceil(dax_df.no_shares[i]/population))
dax_df['shares_pP'] = shares_pP

In [92]:
dax_df['in_posession'] = dax_df['company'].map(in_posession)

In [93]:
to_buy=[]
for i in range(0,len(dax_df)):
    if dax_df.shares_pP[i]-dax_df.in_posession[i]>0:
        to_buy.append(dax_df.shares_pP[i]-dax_df.in_posession[i])
    else:
        to_buy.append(0)
dax_df['to_buy']=to_buy

In [94]:
dax_df

,company,no_shares,shares_pP,in_posession,to_buy
0,adidas,178.54,3,3,0
1,Airbus,789.75,10,0,10
2,Allianz,401.59,5,5,0
3,BASF,918.48,12,22,0
4,Bayer,982.42,12,12,0
5,Beiersdorf,226.82,3,3,0
6,BMW,586.68,8,8,0
7,Brenntag,154.50,2,2,0
8,Commerzbank,1252.36,16,20,0
9,Continental,200.01,3,10,0
10,Covestro,189.95,3,2,1
11,Daimler Truck,0.00,0,7,0
12,Deutsche Bank,2035.24,25,25,0
13,Deutsche Börse,183.74,3,2,1
14,Deutsche Post,1198.74,15,15,0
15,Deutsche Telekom,4972.70,60,58,2
16,E.ON,2610.38,32,32,0
17,Fresenius,557.55,7,4,3
18,Hannover Rück,120.57,2,0,2
19,HeidelbergCement,186.19,3,2,1
20,Henkel vz.,165.21,2,5,0
21,Infineon,1302.23,16,14,2
22,Mercedes-Benz Group (ex Daimler),1069.44,13,13,0
23,Merck,129.24,2,2,0
24,MTU Aero Engines,53.71,1,1,0
25,Münchener Rückversicherungs-Gesellschaft,137.64,2,2,0
26,Porsche,0.00,0,0,0
27,Porsche Automobil vz.,153.13,2,0,2
28,QIAGEN,227.72,3,3,0
29,Rheinmetall,43.38,1,0,1
30,RWE,743.84,9,7,2
31,SAP,1167.11,15,15,0
32,Sartorius vz.,34.19,1,1,0
33,Siemens,788.80,10,10,0
34,Siemens Energy,792.19,10,9,1
35,Siemens Healthineers,1119.39,14,14,0
36,Symrise,139.77,2,0,2
37,Volkswagen (VW) vz.,206.20,3,0,3
38,Vonovia,795.85,10,15,0
39,Zalando,258.97,4,0,4